name: Run EasyControl Script Once

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-image:
    runs-on: ubuntu-latest
    # Only run if generated_image.png doesn't exist
    if: "!contains(github.event.commits[0].added, 'generated_image.png') && !contains(github.event.commits[0].modified, 'generated_image.png')"

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Run the image generation script
      - name: Generate image
        run: |
          python generate_image.py

      # Commit the generated image
      - name: Commit generated image
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add generated_image.png
          git commit -m "Add generated image from EasyControl" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
